const ignoreWords = ["want", 
                    "a",
                     "at",
                    "the", 
                    "in", 
                    "ve", 
                    "re", 
                    "an", 
                    "as", 
                    "can", 
                    "and", 
                    "is", 
                    "what", 
                    "need", 
                    "of", 
                    "with", 
                    "to", 
                    "who", 
                    "do", 
                    "it", 
                    "if", 
                    "you", 
                    "for", 
                    "i", 
                    "your", 
                    "not", 
                    "only", 
                    "been",
                    "com", 
                    "dc",
                    "we",
                    "are",
                    "but",
                    "carrus",
                    "io",
                    "ivy"];

export default ignoreWords;
